name: 'medical_warehouse'
version: '1.0.0'

profile: 'medical_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_warehouse:
    staging:
      schema: staging       # staging models go here
      +materialized: view   
    marts:
      schema: marts         # dimensional models go here
      +materialized: table  
