medical_warehouse:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev

